In [1]:
import numpy as np
import pandas as pd
import numpy.testing as npt

import sys
sys.path.append('..')
from lib import *
from lib.maxent import *

from numba import jit

In [82]:
q = naminoacids
L = 9
prng = np.random

In [83]:
# test: should be uniform over all integers from 0 to 19 other than two
np.unique(((2 + prng.randint(1, q, size=(10000)))%q), return_counts=1)

(array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19]),
 array([509, 544, 497, 517, 551, 556, 535, 523, 537, 541, 526, 545, 491,
        520, 512, 502, 496, 578, 520]))

In [84]:
def local_jump(x, q, prng=None):
    if prng is None:
        prng = np.random
    xnew = x.copy()
    index = prng.randint(len(x))
    xnew[index] = (x[index] + prng.randint(1, q))%q
    return xnew

In [87]:
local_jump(x0, q, prng=prng)

array([17, 12,  6,  0,  0,  2,  3,  6, 10])

In [88]:
%timeit local_jump(x0, q, prng=prng)

15.7 µs ± 373 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [89]:
@jit(nopython=True)
def local_jump_jit(x, q, seed=None):
    prng = np.random
    if not (seed is None):
        np.random.seed(seed)
    xnew = x.copy()
    index = prng.randint(len(x))
    xnew[index] = (x[index] + prng.randint(1, q))%q
    return xnew

In [90]:
local_jump_jit(x0, q)

array([17, 10,  6,  6,  0,  2,  3,  6, 10])

In [91]:
%timeit local_jump_jit(x0, q)

629 ns ± 14.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
